// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeJZiUHHEMUWLVMAWkY1eQyc7VkkkZHxg',
    appId: '1:453102291969:web:a711dc0fb155069d9c0400',
    messagingSenderId: '453102291969',
    projectId: 'health-pal-4fd32',
    authDomain: 'health-pal-4fd32.firebaseapp.com',
    storageBucket: 'health-pal-4fd32.firebasestorage.app',
    measurementId: 'G-ZRRWX9P3DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlXwnVzIu-rGhK5rRXCV96Q2vfr5MAEwQ',
    appId: '1:453102291969:android:8452fcba8cb3dc469c0400',
    messagingSenderId: '453102291969',
    projectId: 'health-pal-4fd32',
    storageBucket: 'health-pal-4fd32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbyyeMC8hU03GTObkapo08w71u6KKfBhA',
    appId: '1:453102291969:ios:df8770ba4254e2c09c0400',
    messagingSenderId: '453102291969',
    projectId: 'health-pal-4fd32',
    storageBucket: 'health-pal-4fd32.firebasestorage.app',
    iosBundleId: 'com.example.da1',
  );
}
